name = "nm-chronicles-production"
main = "dist/nm-chronicles-cloudflare/server/server.mjs"
compatibility_date = "2026-07-02"
account_id = "4eda8255125394a17293a14fc5cdeaac"

[build]
command = "npm run build:cloudflare"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true