name = "nm-chronicles"
main = "src/cloudflare/worker.ts"
compatibility_date = "2026-07-02"
account_id = "4eda8255125394a17293a14fc5cdeaac"

[env.production]

[build]
command = "npm run build:cloudflare"

[build.upload]
dir = "dist/nm-chronicles-cloudflare/browser"
